services:
  mysql-db:
    container_name: mysql-db-hackerton2025
    image: mysql:9.0
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_DB_PASSWORD
    ports:
      - $MYSQL_DB_LOCAL_PORT:$MYSQL_DB_DOCKER_PORT
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

  # nestjs-app:
  #   container_name: nestjs-app-hackerton2025
  #   # depends_on:
  #   #   - mysql-db
  #   build: ./backend
  #   restart: unless-stopped
  #   env_file: ./.env
  #   ports:
  #     - $NESTJS_APP_LOCAL_PORT:$NESTJS_APP_DOCKER_PORT
  #   environment:
  #     - DB_HOST=$MYSQL_DB_HOST
  #     - DB_USER=$MYSQL_DB_USERNAME
  #     - DB_PASSWORD=$MYSQL_DB_PASSWORD
  #     - DB_DATABASE=$MYSQL_DB_DATABASE
  #     - DB_PORT=$MYSQL_DB_DOCKER_PORT
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./backend:/dist
  #     - /app/node_modules
  #   networks:
  #     - default
