# syntax = docker/dockerfile:1

# Adjust NODE_VERSION as desired
ARG NODE_VERSION=23.3.0
FROM node:${NODE_VERSION}-slim AS base

LABEL fly_launch_runtime="NestJS"

# NestJS app lives here
WORKDIR /app

# Set production environment
ENV NODE_ENV="production"

# Install pnpm
ARG PNPM_VERSION=9.15.0
RUN npm install -g pnpm@$PNPM_VERSION

# ENV로 설정하여 이후에 사용 가능
ENV MYSQL_DB_PORT=$MYSQL_DB_PORT
ENV MYSQL_DB_HOST=$MYSQL_DB_HOST
ENV MYSQL_DB_PASSWORD=$MYSQL_DB_PASSWORD
ENV MYSQL_DB_USERNAME=$MYSQL_DB_USERNAME
ENV MYSQL_DB_DATABASE=$MYSQL_DB_DATABASE

# Throw-away build stage to reduce size of final image
FROM base AS build

# Install packages needed to build node modules
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential node-gyp pkg-config python-is-python3

# Install node modules
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod=false

# Copy application code
COPY . .

# Build application
RUN pnpm run build


# Final stage for app image
FROM base

# Copy built application
COPY --from=build /app /app

# Start the server by default, this can be overwritten at runtime
EXPOSE 3000
CMD [ "pnpm", "run", "start" ]
